# Generated by Django 3.2.4 on 2021-09-13 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puticasa', '0002_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='users',
            field=models.ManyToManyField(through='puticasa.Resident', to=settings.AUTH_USER_MODEL),
        ),
    ]
